version: '3.7'

# Docker configuration for development
#
# If you need local adjustments, use a Docker compose override file.

services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DINING_DEBUG: 'true'
      DINING_SECRET_KEY: 'hello'
      DINING_DATABASE_URL: postgres://dining:dining@db/dining
    volumes:
      - .:/app/src
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: dining
      POSTGRES_PASSWORD: dining
      POSTGRES_DB: dining
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db:
